heightfin="-"
wcmssg1=Welcome to Drubuntu - Setup part 2
wcmssg2=This assistent would do everything for you. 
wcmssg3=This is just the basic installation later you'll be able to add more features and set up your the desktop of you like.
aktcmssg=Hit any key to continue!
bppmssg=Be pacient please ...
dlbcmssg=Drubuntu downloads all basic components now
ap2setupmssg=Preparing Appache 2 for Drupal
d7installmssg=Installing Drupal 7
d8installmssg=Installing Drupal 8
drushinstallmssg=Installing Drush
createdirmsg=Creating folders ...
createfilesmsg=Creating files ...
createmysqldbmssg=Create mysql Database ---
prpusrflsmssg=Preparing user files ...
createusermssg=create user
disablerootmssg=disabeling root account
plymoutlogomessage=changeig Plymouth Boot Logo
roothintmssg=You are logged in as root. Answer the questions and log in with your specified user name!
enterusernamemmsg=Enter the username you like to use later and hit [ENTER]: 
$wwoddltumssg=Wich Version of Drupal do you like to use? 
drupal7inputdatamssg=Now we need some Data for Drupal7:
enterd7domainmssg=Enter the domain for Drupal 7 and press [ENTER]: 
enterd7dbusermssg=Enter the name of Your Drupal 7 database user and press [ENTER]: 
enterd7dbpassmssg=Enter the password for Your Drupal 7 Database user and press [ENTER]: 
$drupal7inputdatamssg=Now we need some Data for Drupal8:
enterd8domainmssg=Enter the domain for drupal 8 and press [ENTER]: 
enterd8dbusermssg=Enter the name of Your Drupal 8 database user and press [ENTER]: 
enterd8dbpassmssg=Enter the password for Your Drupal 8 Database user and press [ENTER]: 
thanksmssg=Thank You!
