#!/bin/bash
#this is the ony file where main functions will be triggerd. We need to source functions to make sure everything goes well!
lsb_version=`lsb_release --release | cut -f2`
if [ $LANG=="de_DE.UTF-8" ];then
source de
else
source en
fi
source colors
source functionsxenial
source filetemplates

dlbase()
{
echo -ne  '                                                                                          (0%)\r'
server
echo -ne '   #                                                                                      (10%)\r'
core
echo -ne '   #########                                                                              (20%)\r'
crfiles
echo -ne '   ###################                                                                    (30%)\r'
drupal
echo -ne '   #######################################                                                (50%)\r'
cleanup
echo -ne '   #################################################                                      (60%)\r'
sleep 1
echo -ne '   ###########################################################                            (70%)\r'
sleep 1
echo -ne '   #####################################################################                  (80%)\r'
sleep 1
echo -ne '   ###############################################################################        (90%)\r'
sleep 1
echo -ne '   ###################################################################################### (100%)\r'
echo -ne '\n'
sleep 3
}
#first echo creates space after sudo input
clear
echo ""
echo -e " ${lightblue}  ${wcmssg1} ${nc}"
echo -e " ${lightblue}  ${wcmssg2} ${nc}"
echo -e " ${lightblue}  ${wcmssg3} ${nc}"
echo ""
echo -e "${white}${nc}"
# > /dev/null to hide the output
dlbase
exit
