#!bin/bash
#This file holds all common variables for your installation of drubuntu. they are accessable in every userprofile
if ! [ $HOME/.bash_aliases ]; then
echo ". /.drubuntu/.bash_aliases" >$HOME/.bash_aliases
fi
#system repair commands
alias dru-system-repair="sudo apt-get autoclean; sudo apt-get -y autoremove; sudo dpkg -y --clear-avail; sudo apt-get update; sudo apt-get -y dist-upgrade"
#All variables and commands from here added by the installer. automaticly.
drubaseidir=/opt/.drubuntu
scrdir=$drubaseidir/scripts/
drfeatures="$scrdir"features
drcreatesite="$scrdir"createsite
drcreatesubdomain="$scrdir"ceatesubdomain
drsetip="$scrdir"setip
drupdate="$scrdir"/update
#features
alias dru-features='bash "$drfeatures" --help'
alias dru-install-plymouthlogo='bash "$drfeatures" --plymouth'
alias dru-install-ftp='bash "$drfeatures" --proftpd'
alias dru-install-webexplangs='bash "$drfeatures" --webexplangs'
alias dru-install-aptana='bash "$drfeatures" --aptana'
alias dru-install-aptanagit='bash "$drfeatures" --aptana-git'
alias dru-install-aptanaxdebug='bash "$drfeatures" --aptana-xdebug'
alias dru-install-xdebug='bash "$drfeatures" --xdebug'
alias dru-install-desktops='bash "$drfeatures" --desktops'
alias dru-install-browsers='bash "$drfeatures" --browsers'
alias dru-install-atom='bash "$drfeatures" --atom'
#help
alias dru-quickhelp="more "$drubasedir"quickhelp.txt"
#scripts
alias dru-addsite='sudo bash "$drcreatesite"'
alias dru-addsubdomain='sudo bash "$drcreatesubdomain"'
alias dru-update='sudo bash "$drupdate"'
alias dru-setip='sudo bash "$drsetip"'
#aliases without scripts
alias dru-install-phpmyadmin="sudo apt-get install phpmyadmin"
alias dru-mysql-secure="mysql_secure_installation"
alias dru-set-publichtml-default="echo 'cd public_html'>>~/.bashrc"
